on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.TOKEN_RELEASE_PLEASE }}

      - name: Generate plasma 5 plasmoid package
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd ./src/plasma5
          zip -r ../../plasmusic-toolbar-${{steps.release.outputs.tag_name}}-plasma5.plasmoid .

      - name: Generate plasma 6 plasmoid package
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd ./src/plasma6
          zip -r ../../plasmusic-toolbar-${{steps.release.outputs.tag_name}}-plasma6.plasmoid .

      - name: Upload plasmoid package to release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          - gh release upload ${{ steps.release.outputs.tag_name }} ./plasmusic-toolbar-${{steps.release.outputs.tag_name}}-plasma5.plasmoid ./plasmusic-toolbar-${{steps.release.outputs.tag_name}}-plasma6.plasmoid
